name       : haskell-src
version    : 1.0.3.0
release    : 4
source     :
    - http://hackage.haskell.org/package/haskell-src-1.0.3.0/haskell-src-1.0.3.0.tar.gz : b4b4941e8883da32c3f2b93f3ecdd5cff82ff9304cb91e89850b19095c908dbc
license    : BSD-3-Clause
component  : programming.haskell
summary    : The haskell-src package provides support for manipulating Haskell source code.
description: |
    The haskell-src package provides support for manipulating Haskell source code.
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-happy
    - haskell-syb-devel
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
