name       : haskell-src
version    : 1.0.2.0
release    : 3
source     :
    - http://hackage.haskell.org/package/haskell-src-1.0.2.0/haskell-src-1.0.2.0.tar.gz : 2a25ee5729230edddb94af8d9881efbc1d8798bd316097f4646749cb2fa491a6
license    : BSD-3-Clause
component  : programming.haskell
summary    : The haskell-src package provides support for manipulating Haskell source
    code.
description: |
    The haskell-src package provides support for manipulating Haskell source code.
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-happy
    - haskell-syb-devel
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
