name       : haskell-src
version    : 1.0.2.0
release    : 1
source     :
    - http://hackage.haskell.org/package/haskell-src-1.0.2.0/haskell-src-1.0.2.0.tar.gz : 2a25ee5729230edddb94af8d9881efbc1d8798bd316097f4646749cb2fa491a6
license    : BSD-3-Clause
component  : programming
summary    : The haskell-src package provides support for manipulating Haskell source code.
description: |
    The haskell-src package provides support for manipulating Haskell source code.
builddeps  :
    - ghc
    - haskell-happy
    - haskell-syb
setup      : |
    sudo ghc-pkg recache
    ghc -threaded Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 haskell-src-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/haskell-src-$version.conf
